### ISSUE TITLE
Site content

### ISSUE THREAD

**Issue by HotelCalifornia** [phillycommunitywireless/phillycommunitywireless#1]
We should start thinking about what content should go on the site as well as the format it should take. 

One thought I had was to provide weekly updates in the form of summaries of the meeting notes, but maybe that would be too much.... minutia? Either way, as it stands, I feel like visitors to the site may get the feeling that either there's no progress being made or that the project is abandoned (like with [the philly mesh project](https://phillymesh.net/)).

Note: treat this less as an "issue" and more as an action item

**Comment by hawc2** [comment]
The weekly updates are a good idea!

**Comment by gwijthoff** [comment]
@HotelCalifornia agreed! Let's talk next week about passing around the weekly meeting writeup duties.
