### ISSUE TITLE
Adjust how nav items are displayed on mobile 

### ISSUE THREAD

**Issue by eugenethreat** [phillycommunitywireless/phillycommunitywireless#106]
Not so pressing at the moment, but something to be mindful of - the more sections we add to the navbar, the more space it will take up on mobile screens - I think the UI would be improved by replacing this list with a button that brings up a menu or something. 

![image](https://github.com/phillycommunitywireless/phillycommunitywireless/assets/45939110/723af5ec-16e8-4582-882e-0ee5a055367d)

**Comment by justinmmeans** [comment]
Working on this currently! Will have staged with pull by Saturday evening.
