### ISSUE TITLE
revamp homepage

### ISSUE THREAD

**Issue by wenxich** [phillycommunitywireless/phillycommunitywireless#112]
as discussed in 7/3 meeting:
- change images to be more recent images (with our current logo)
- replace map image with wifi coverage map
- delete second video (what is community wifi)
- change "current work" to be more descriptive (@hawc2 could you elaborate? would "active networks" be better?)

**Comment by hawc2** [comment]
@wenxich i recently made a few edits, checking off the remaining to dos here

- [ ] change images to be more recent images (with our current logo)
- [ ] replace map image with wifi coverage map
- [ ] delete second video (what is community wifi)
- [ ] change "current work" to be more descriptive
