### ISSUE TITLE
Compress Navbar 

### ISSUE THREAD

**Issue by eugenethreat** [phillycommunitywireless/phillycommunitywireless#118]
Related to https://github.com/phillycommunitywireless/phillycommunitywireless/issues/106 - navbar is getting a bit busy, even on Desktop

**Compress nav to have dropdown menus**

Current Nav:
* Connect
* Volunteer
* Map
* About
* People
* Partners
* FAQ
* Donate (ext. link) 
* Docs (ext. link)
* Language Switcher (eng/esp)

Could be compressed into ... 
About 
* (Current About Page) 
* Map 
* FAQ
* Docs

Connect / 'Get Involved'? 
* Connect 
* Volunteer 

People 
* People (People) 
* Partners
* Funders

**Comment by leannepcw** [comment]
Would prefer to see it compressed to:

Get Connected
- Connect
- Volunteer
- Support Us
About Us
- About
- People
- Partners
- Funders
- FAQ
- Getting Here
Map
Docs
EN/ES

To discuss more with Alex.
