### ISSUE TITLE
Prevent CI/CD workflow from deploying on PR CI builds

### ISSUE THREAD

**Issue by HotelCalifornia** [phillycommunitywireless/phillycommunitywireless#16]
as seen in #15 the github action workflow fails because the PR author (dependabot) doesn't have proper permissions to push to the repo.

this works in our favour for the moment, because pull request builds shouldn't be deployed over the version from master. however, if someone with permissions were to make a PR, the workflow would successfully deploy.

the fix should be fairly straightforward, and will just require a minor rework of our github action workflow so that the separate steps (build and deploy) are only triggered both at once on master, otherwise run build only.

**Comment by hawc2** [comment]
@timtraversy is this something you can take a look at? or will it be fixed by other redesigns?

**Comment by hawc2** [comment]
@addiebarron what are your thoughts on this?

**Comment by hawc2** [comment]
@HotelCalifornia are you available to help resolve this ticket? There's currently a stalled pull request from dependabot...

**Comment by hawc2** [comment]
we're going to close this ticket and delete the dependabot.yml file to avoid further build failures

**Comment by dzygmundfelt** [comment]
This was done in https://github.com/phillycommunitywireless/phillycommunitywireless/pull/73
