### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by HotelCalifornia** [phillycommunitywireless/phillycommunitywireless#2]
I think it would be useful to provide a how-to guide here in the repository so that anyone who wants to can publish content. This document might look something like this:

- quick guide
  - i.e. how to add/edit content using the GitHub UI
- advanced guide
  - forking(?)
  - installing git/hugo
  - adding/editing content
  - testing locally
  - pushing/making PR

**Comment by gwijthoff** [comment]
@HotelCalifornia fantastic idea. Would you like to take the lead on that? There should be some pretty standard resources available for the advanced guide portion that we can just link to. But for the quick guide, I can get you started with some initial bearings:

- the homepage text and People and Resources pages are all generated from markdown files in the `content/` directory.
- blog posts / updates live in the `content/updates/` directory.
- HTML for page layouts can be found in `themes/pcwp-hugo/layouts` and CSS is located at `themes/pcwp-hugo/assets/scss`, though these are probably not something we'll invite a large group of people to edit

It occurs to me now that I'm building the site from the `docs/` folder, which means that it has to be generated locally using the `$ hugo` terminal command. Editing the markdown files using the GitHub UI likely won't do anything to change the website itself. Unless you have any experience changing the source of a Hugo build. A colleague has mentioned using [GitHub Actions](https://github.com/features/actions) to automate the process, but that's beyond my skills.

Also: just so you know, the site's CSS uses [tachyons](https://tachyons.io/), which is great for rapid prototyping, but can be confusing at first.

**Comment by gwijthoff** [comment]
Curious if the [repo's wiki](https://github.com/gwijthoff/phillycommunitywireless/wiki) or README is the best place for this documentation.

**Comment by HotelCalifornia** [comment]
> Would you like to take the lead on that?

Sure, I can do it.

> A colleague has mentioned using [GitHub Actions](https://github.com/features/actions) to automate the process, but that's beyond my skills.

I haven't played with Actions yet much myself, but I have worked with similar systems, so I can take a swing at that too.

> Curious if the [repo's wiki](https://github.com/gwijthoff/phillycommunitywireless/wiki) or README is the best place for this documentation.

I could see it going either way, but for sake of keeping things organized I think it would be better to do this in the wiki (with link(s) in the readme)

**Comment by HotelCalifornia** [comment]
> I haven't played with Actions yet much myself, but I have worked with similar systems, so I can take a swing at that too.

In the last week I have done a fair amount of work familiarizing myself with this, and it's pretty straightforward.

@gwijthoff mentioned potentially using [forestry](https://forestry.io) as a CMS. I think it looks promising, but one thing to keep in mind is that their free plan supports only up to 3 editor accounts per site. This isn't a problem in and of itself, but it might make things a little more difficult if the goal was to rotate posting responsibility between more people than that... 

either way, one more thing to think about (and since nothing is set in stone, there's no reason we can't add/subtract in the future if our chosen approach doesn't work out)

**Comment by gwijthoff** [comment]
@HotelCalifornia great example of user friendly documentation on a crowdsourced Hugo site on the [When They Came Down](https://whentheycamedown.com/) project. Here's the [repo](https://github.com/Gorcenski/whentheycamedown). And [here's](https://scholarslab.lib.virginia.edu/blog/participating-in-statue-removal-history-crowdsourcing/) a detailed tutorial by someone at the UVA Scholar's Lab on how to contribute to the site.

**Comment by hawc2** [comment]
@addiebarron has taken a shot at something like is described here in the Editing the Docs page here: https://docs.phillycommunitywireless.org/en/latest/edit-docs/

I wonder how much more is necessary at this point, or if this issue can be closed?
