### ISSUE TITLE
Add a section for partner org logos to homepage

### ISSUE THREAD

**Issue by addiebarron** [phillycommunitywireless/phillycommunitywireless#41]
Alex requested this [in Slack](https://pcwproject.slack.com/archives/C02C73XDX0X/p1639171137002100).

A section in the homepage would probably have to be hard-coded into the theme (`themes/pcw-hugo-theme`), the same way the "Contact us" section currently is. It would be great if it was customizable via a config file or front matter, probably using a [Hugo menu](https://gohugo.io/content-management/menus/). 

Anyone can take a crack at this and make a PR, but if not I'll probably get to it in the next few weeks!

**Comment by hawc2** [comment]
@addiebarron does this seem doable this summer?

**Comment by dzygmundfelt** [comment]
@hawc2 could you provide the list of partner orgs with their corresponding logos?

Also I'm thinking it makes sense to make another page a la https://phillycommunitywireless.org/partners/ that we'd put this on, and we could include a blurb for each partner org and embed a link in their image. Let me know if that sounds good.

**Comment by gwijthoff** [comment]
@dzygmundfelt there are [two lists currently on the People page](https://github.com/phillycommunitywireless/phillycommunitywireless/blob/master/content/en/people.md#norris-square-community-partners), one for Norris Square Community Partners and one for Philly Community Partners. @hawc2 would know how up-to-date these lists are.

I agree that a separate Partners page is a good idea for this info!

**Comment by dzygmundfelt** [comment]
@hawc2 should I just grab the logos from all the orgs in the lists that @gwijthoff linked to in the previous comment? Not sure if it's something we would need to ask permission for.

**Comment by hawc2** [comment]
yeah that sounds good. no need for permission. just slack me if you have trouble finding something. if we need a certain file type we can ask each org's rep

**Comment by wenxich** [comment]
i was thinking of taking this issue on and making something similar to the funders page i made here: #104

but let me know if there's another ui design direction we want to take before i begin working on it!

**Comment by hawc2** [comment]
that sounds good @wenxich. 

the only thing i'd say is more important is also more complicated, #96, to set up a way we can preview changes live on Github. it would make it easier for me to review feature upgrades like this #41 ticket for adding logos for partners
