### ISSUE TITLE
Github actions preview of website

### ISSUE THREAD

**Issue by hawc2** [phillycommunitywireless/phillycommunitywireless#96]
would be great if we could set up a preview of pull request changes

**Comment by hawc2** [comment]
@dzygmundfelt @eugenethreat a good example of what would be ideal here is available on this other repository I work on, this pull request shows you how the Programming Historian uses Netlify to create a preview of the build to evaluate changes before merging: https://github.com/programminghistorian/jekyll/pull/3284

**Comment by eugenethreat** [comment]
Done - left some additional information/context in JIRA.
