### ISSUE TITLE
attribution of photo credits

### ISSUE THREAD

**Issue by hawc2** [phillycommunitywireless/phillycommunitywireless#98]
how can we add little text below each photo with attribution of credits for taking photos or other descriptors of the photos?

**Comment by hawc2** [comment]
@gwijthoff do you know how we could start doing this on our Hugo site?

**Comment by hawc2** [comment]
@eugenethreat maybe this is something you can explore? here's an example of what i have in mind: https://discourse.gohugo.io/t/adding-captions-to-images/40102. if this is relatively straightforward could you work with @leannepcw on adding captions to images, we can credit photographers and describe image content briefly

**Comment by eugenethreat** [comment]
@hawc2 Leaving a comment in JIRA as well but yes I'll take a stab at this this week - just messaged Wenxi to make sure they haven't started on this at all.

**Comment by eugenethreat** [comment]
![image](https://github.com/phillycommunitywireless/phillycommunitywireless/assets/45939110/4b1b45b2-679e-4cd2-9ace-ba90393f373c)

Have to run for the tech meeting but here's a quick little thing I threw together - I think italics are good for captions, and I personally like having image credits on a newline (the font could definitely be made smaller for both caption and credits).

**Comment by hawc2** [comment]
@eugenethreat looks great to me, thank you. The main thing we'll need is a description in our readme for how to do this easily so @leannepcw can replicate it across the website

**Comment by eugenethreat** [comment]
> @eugenethreat looks great to me, thank you. The main thing we'll need is a description in our readme for how to do this easily so @leannepcw can replicate it across the website

Added instructions to READme and merging now.
